=== ims-tcl/DeRE/specs/dere.dtd
<!ELEMENT deREschema (spantypes | frames)*>
<!ATTLIST deREschema name CDATA #REQUIRED>
<!ATTLIST deREschema version CDATA #REQUIRED>
<!ATTLIST deREschema author CDATA #REQUIRED>

<!ELEMENT uniontype EMPTY>
<!ATTLIST uniontype name CDATA #REQUIRED>
<!ATTLIST uniontype includes CDATA #REQUIRED>
<!ELEMENT spantypes (span)*>
<!ELEMENT frames (frame)*>

<!ATTLIST frame name CDATA #IMPLIED>
<!ELEMENT frame (slot)*>

<!ELEMENT slot EMPTY>
<!ATTLIST slot maxcardinality CDATA #IMPLIED>
<!ATTLIST slot mincardinality CDATA #IMPLIED>
<!ATTLIST slot name CDATA #REQUIRED>
<!ATTLIST slot types CDATA #REQUIRED>
<!ATTLIST slot cardinality CDATA #IMPLIED>

<!ELEMENT span EMPTY>
<!ATTLIST span name CDATA #IMPLIED>

=== ims-tcl/DeRE/data/frame-specifications/xmlv1/bionlpst-simplified.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<!-- http://2011.bionlp-st.org/home/genia-event-extraction-genia -->
<deREschema name="BioNLP-ST 2009" version="0.01" author="Roman Klinger">
  <spantypes>
    <span name="Gene"/>
    <span name="Positive Regulation Trigger" anchors="Positive Regulation"/>
    <span name="Negative Regulation Trigger" anchors="Negative Regulation"/>
    <span name="Binding Trigger" anchors="Binding"/>
  </spantypes>
  <frames>
    <frame name="Positive Regulation">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Cause" types="Gene" mincardinality="0" maxcardinality="1"/>
      <slot name="Theme" types="Gene,Positive Regulation,Negative Regulation" cardinality="1"/>
    </frame>
    <frame  name="Negative Regulation">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Cause" types="Gene" mincardinality="0" maxcardinality="1"/>
      <slot name="Theme" types="Gene,Positive Regulation,Negative Regulation" cardinality="1"/>
    </frame>
    <frame name="Binding">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Theme" types="Gene" mincardinality="1"/>
    </frame>
  </frames>
</deREschema>

=== ims-tcl/DeRE/specs/chemical.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<deREschema name="Chemical Disease Relation" version="0.01" author="Hendrik Schuff">
  <spans>
    <span name="Chemical" predict="True"/>
    <span name="Disease" predict="True"/>
  </spans>
  <frames>
    <frame name="Direct">
      <slot name="Chemical" types="span:Chemical" cardinality="1"/>
      <slot name="Disease" types="span:Disease" cardinality="1"/>
    </frame>
    <frame name="Indirect">
      <slot name="Chemical" types="span:Chemical" cardinality="1"/>
      <slot name="Disease" types="span:Disease" cardinality="1"/>
    </frame>
  </frames>
</deREschema>

=== ims-tcl/DeRE/specs/bionlpst_reduced.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<!-- http://2011.bionlp-st.org/home/genia-event-extraction-genia -->
<deREschema name="BioNLP-ST 2009" version="0.01" author="Roman Klinger">
  <!--<uniontype name="Regulation" includes="Regulation,Positive Regulation,Negative Regulation"/>-->
  <spans>
    <span name="Gene_expression" predict="True"/>
    <span name="Protein" predict="False"/>
    <span name="Transcription" predict="True"/>
    <span name="Protein_catabolism" predict="True"/>
    <span name="Phosphorylation" predict="True"/>
    <span name="Localization" predict="True"/>
  </spans>
  <frames>
    <frame name="Gene_expression">
      <slot name="Gene_expression" types="span:Gene_expression" cardinality="1"/>
      <slot name="Theme" types="Protein" cardinality="1"/>
    </frame>
    <frame name="Transcription">
      <slot name="Transcription" types="span:Transcription" cardinality="1"/>
      <slot name="Theme" types="Protein" cardinality="1"/>
    </frame>
    <frame name="Protein_catabolism">
      <slot name="Protein_catabolism" types="span:Protein_catabolism" cardinality="1"/>
      <slot name="Theme" types="Protein" cardinality="1"/>
    </frame>
    <frame name="Phosphorylation">
      <slot name="Phosphorylation" types="span:Phosphorylation" cardinality="1"/>
      <slot name="Theme" types="Protein" cardinality="1"/>
    </frame>
    <frame name="Localization">
      <slot name="Localization" types="span:Localization" cardinality="1"/>
      <slot name="Theme" types="Protein" cardinality="1"/>
    </frame>
  </frames>
</deREschema>

=== ims-tcl/DeRE/data/frame-specifications/xmlv1/bionlpst.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<!-- http://2011.bionlp-st.org/home/genia-event-extraction-genia -->
<deREschema name="BioNLP-ST 2009" version="0.01" author="Roman Klinger">
  <uniontype name="Regulation" includes="Regulation,Positive Regulation,Negative Regulation"/>
  <spantypes>
    <span name="Gene"/>
    <span name="Trigger"/>
  </spantypes>
  <frames>
    <frame name="Regulation">
      <slot name="EventTrigger" types="Trigger" mincardinality="1" maxcardinality="1"/>
      <slot name="Cause" types="Gene" mincardinality="0" maxcardinality="1"/>
      <slot name="Theme" types="Gene,Regulation,Positive Regulation,Negative Regulation" mincardinality="1" maxcardinality="1"/>
    </frame>
    <frame name="Positive Regulation">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Cause" types="Gene" mincardinality="0" maxcardinality="1"/>
      <slot name="Theme" types="Gene,Regulation,Positive Regulation,Negative Regulation" cardinality="1"/>
    </frame>
    <frame  name="Negative Regulation">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Cause" types="Gene" mincardinality="0" maxcardinality="1"/>
      <slot name="Theme" types="Gene,Regulation,Positive Regulation,Negative Regulation" cardinality="1"/>
    </frame>
    <frame name="Binding">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Theme" types="Gene" mincardinality="1"/>
    </frame>
    <frame name="Transcription">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Theme" types="Gene" cardinality="1"/>
    </frame>
    <frame name="Protein Catabolism">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Theme" types="Gene" cardinality="1"/>
    </frame>
    <frame name="Phosporylization">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Theme" types="Gene" cardinality="1"/>
    </frame>
    <frame name="Localization">
      <slot name="EventTrigger" types="Trigger" cardinality="1"/>
      <slot name="Theme" types="Gene" cardinality="1"/>
    </frame>
  </frames>
</deREschema>

=== ims-tcl/DeRE/data/frame-specifications/xmlv1/subjaspsa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<!-- http://www.romanklinger.de/usagecorpus/ -->
<!-- http://www.romanklinger.de/scare/ -->
<deREschema name="Aspect-based sentiment analysis" version="0.01" author="Roman Klinger">
  <spantypes>
    <span name="subjective"/>
    <span name="aspect"/>
  </spantypes>
  <frames>
    <frame name="Positive"><slot name="phrase" types="subjective"/></frame>
    <frame name="Negative"><slot name="phrase" types="subjective"/></frame>
    <frame name="Neutral"><slot name="phrase" types="subjective"/></frame>
    <frame name="Foreign"><slot name="phrase" types="aspect"/></frame>
    <frame name="Related"><slot name="phrase" types="aspect"/></frame>
    <frame name="Relation">
      <slot name="Subjective Phrase" types="Positive,Negative,Neutral,subjective" cardinality="1"/>
      <slot name="Aspect Phrase" types="Forein,Related,aspect" cardinality="1"/>
    </frame>
  </frames>
</deREschema>

=== ims-tcl/DeRE/data/frame-specifications/xmlv1/tmp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<!-- http://www.romanklinger.de/usagecorpus/ -->
<!-- http://www.romanklinger.de/scare/ -->
<deREschema name="Aspect-based sentiment analysis" version="0.01" author="Roman Klinger">
  <spantypes>
    <span type="subjective"/>
    <span type="aspect"/>
  </spantypes>
  <frames>
    <frame name="Positive"><slot name="phrase" type="subjective"/>
    <frame name="Negative"><slot name="phrase" type="subjective"/>
    <frame name="Neutral"><slot name="phrase" type="subjective"/>
    <frame name="Foreign"><slot name="phrase" type="aspect"/>
    <frame name="Related"><slot name="phrase" type="aspect"/>
    <frame name="Relation">
      <slot name="Subjective Phrase" types="Positive,Negative,Neutral,subjective" cardinality="1"/>
      <slot name="Aspect Phrase" types="Forein,Related,aspect" cardinality="1"/>
    </frame>
  </frames>
<deREschema>

=== ims-tcl/DeRE/specs/quote.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deREschema SYSTEM "dere.dtd">
<!-- http://2011.bionlp-st.org/home/genia-event-extraction-genia -->
<deREschema name="Quoted Speech Attribution" version="0.01" author="Sean Papay">
  <spans>
    <span name="PERSON" predict="True"/>
    <span name="QUOTE" predict="True"/>
  </spans>
  <frames>
    <frame name="QUOTE">
      <slot name="QUOTE" types="span:QUOTE" cardinality="1"/>
      <slot name="speaker" types="PERSON" maxcardinality="1"/>
      <slot name="addressee" types="PERSON" maxcardinality="1"/>
    </frame>
  </frames>
</deREschema>
